# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad en gramos'),
        ),
    ]
