# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20160918_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Delivered'), (2, 'Rejected')], default=0),
        ),
    ]
