# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-23 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad en gramos')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo por Kilogramo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
