# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
