# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160914_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad en gramos'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo por Kilogramo'),
        ),
    ]
